"""Command-line glue for the userdir example. FROZEN; part of the trusted computing base.

This file is deliberately small. It does not build any SQL itself: the only SQL text it
ever executes is the string returned by the Dafny-compiled `App.Search`, whose
postcondition is proven against the approved specification (spec/UserdirSpec.dfy).

What it does, and why each step is a trust assumption (see docs/TCB.md):
  * rejects input that cannot be encoded as UTF-8 or contains NUL, matching the
    `Sql.Data` type (no NUL) that the proof assumes;
  * switches off SQLite's double-quoted-string misfeature, so a double-quoted
    identifier is never silently reinterpreted as a string literal;
  * executes the text with the standard sqlite3 module.

Usage:
  userdir.py --build DIR init DB     create DB from data/seed.sql
  userdir.py --build DIR search DB NAME
DIR is the directory generated by `dafny translate py` for the App module.
"""
import argparse
import os
import sqlite3
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SEED = os.path.join(HERE, "..", "data", "seed.sql")


def load_app(build_dir):
    sys.path.insert(0, build_dir)
    import _dafny  # noqa: E402  (Dafny runtime, generated next to the app)
    import App  # noqa: E402
    return _dafny, App


def to_dafny(_dafny, text):
    return _dafny.SeqWithoutIsStrInference(map(_dafny.CodePoint, text))


def check_data(text):
    """Return an error message if `text` is not a valid Sql.Data value, else None."""
    try:
        text.encode("utf-8")
    except UnicodeEncodeError:
        return "input rejected: not valid Unicode text"
    if "\x00" in text:
        return "input rejected: NUL character"
    return None


def connect(path):
    db = sqlite3.connect(path)
    db.setconfig(sqlite3.SQLITE_DBCONFIG_DQS_DML, False)
    db.setconfig(sqlite3.SQLITE_DBCONFIG_DQS_DDL, False)
    return db


def main(argv):
    ap = argparse.ArgumentParser(prog="userdir")
    ap.add_argument("--build", required=True, help="directory generated by dafny translate py")
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("init").add_argument("db")
    s = sub.add_parser("search")
    s.add_argument("db")
    s.add_argument("name")
    args = ap.parse_args(argv)

    if args.cmd == "init":
        if os.path.exists(args.db):
            os.remove(args.db)
        db = sqlite3.connect(args.db)
        with open(SEED, encoding="utf-8") as f:
            db.executescript(f.read())
        db.commit()
        return 0

    problem = check_data(args.name)
    if problem:
        print(problem, file=sys.stderr)
        return 2
    _dafny, App = load_app(os.path.abspath(args.build))
    sql = App.default__.Search(to_dafny(_dafny, args.name)).VerbatimString(False)
    db = connect(args.db)
    for row in db.execute(sql):
        print("\t".join(str(v) for v in row))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
