"""Functional and exploit tests for userdir. FROZEN.

Run:  python3 -I test_userdir.py --build DIR [--expect-leak]
  --build DIR     directory generated by `dafny translate py` for the App module
  --expect-leak   the exploit tests must SUCCEED (used to show the vulnerable variant leaks)
Without --expect-leak the exploit tests must FAIL to extract anything (verified variant).
"""
import os
import subprocess
import sys
import tempfile
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
GLUE = os.path.join(HERE, "..", "glue", "userdir.py")
BUILD = None
EXPECT_LEAK = False

SECRETS = ["S3CR3T-ALICE-7f3a", "S3CR3T-BOB-91c2", "S3CR3T-OBRIEN-5d0e", "S3CR3T-ZOE-aa14"]


def run_cli(db, *args):
    return subprocess.run([sys.executable, "-I", GLUE, "--build", BUILD, *args],
                          capture_output=True, text=True, encoding="utf-8")


class UserdirTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.tmp = tempfile.TemporaryDirectory()
        cls.db = os.path.join(cls.tmp.name, "users.db")
        r = run_cli(cls.db, "init", cls.db)
        assert r.returncode == 0, r.stderr

    @classmethod
    def tearDownClass(cls):
        cls.tmp.cleanup()

    def search(self, name):
        r = run_cli(self.db, "search", self.db, name)
        return r.returncode, r.stdout, r.stderr

    # ---- functional behaviour (must hold for every variant)
    def test_exact_match(self):
        self.assertEqual(self.search("alice"), (0, "alice\talice@example.org\n", ""))

    def test_apostrophe_in_name(self):
        self.assertEqual(self.search("o'brien"), (0, "o'brien\tobrien@example.org\n", ""))

    def test_unicode_name(self):
        self.assertEqual(self.search("zoë 😀"), (0, "zoë 😀\tzoe@example.org\n", ""))

    def test_unknown_name_gives_nothing(self):
        self.assertEqual(self.search("nobody"), (0, "", ""))

    def test_empty_name_gives_nothing(self):
        self.assertEqual(self.search(""), (0, "", ""))

    def test_nul_is_rejected_before_the_app(self):
        # A NUL cannot be passed in argv, so test the glue's check directly.
        sys.path.insert(0, os.path.dirname(GLUE))
        import userdir
        self.assertIsNotNone(userdir.check_data("a\x00b"))
        self.assertIsNotNone(userdir.check_data("\ud800"))
        self.assertIsNone(userdir.check_data("fine"))

    # ---- exploits
    EXPLOITS = [
        "x') UNION SELECT secret, email FROM users --",
        "x') UNION SELECT secret, secret FROM users WHERE ('1'='1",
        "') OR ('1'='1",
        "alice') OR 1=1 --",
    ]

    def leaked(self, out):
        return any(s in out for s in SECRETS) or len(out.splitlines()) > 1

    def test_exploits(self):
        results = [self.search(e) for e in self.EXPLOITS]
        if EXPECT_LEAK:
            self.assertTrue(any(self.leaked(out) for _, out, _ in results),
                            "expected at least one exploit to leak data from the vulnerable variant")
        else:
            for e, (code, out, err) in zip(self.EXPLOITS, results):
                self.assertEqual((code, out), (0, ""), f"exploit {e!r} produced output {out!r} / {err!r}")


if __name__ == "__main__":
    args = sys.argv[1:]
    BUILD = os.path.abspath(args[args.index("--build") + 1])
    EXPECT_LEAK = "--expect-leak" in args
    # The vulnerable variant is also functionally broken (e.g. for o'brien), so when we only
    # want to demonstrate the exploit, run just the exploit test.
    only = ["UserdirTest.test_exploits"] if EXPECT_LEAK else []
    unittest.main(argv=[sys.argv[0], "-v", *only])
